server:
  port: 8080
  
---
spring:
  jpa:
    # JPA 설정
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  profiles:
    active:
    - db
    - auth
    - client-github

---
cors:
  allowedOrigins: http://localhost:5176
  allowedMethods: GET,POST,PUT,DELETE
  allowedHeaders: "*"

---    
# Mybatis 설정
mybatis:
  # default Package location - resultType의 Alias를 지정합니다.
  type-aliases-package: com.gen.script
  # mapper location - 바라 볼 xml 파일을 지정합니다.
  mapper-locations: classpath:mapper/*.xml
  # column name to camel case - 반환 받는 컬럼명을 CamelCase로 받는 설정을 합니다.
  configuration:
    map-underscore-to-camel-case: true