CREATE TABLE PGI_USER_REFRESH_TOKEN(
	`USER_ID`	VARCHAR(45)	NOT NULL	COMMENT '유저 식별자',
	`REFRESH_TOKEN`	VARCHAR(1000)	NOT NULL	COMMENT '리프레시 토큰',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (USER_ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_USERS(
	`USER_ID`	VARCHAR(45)	NOT NULL	COMMENT '유저 식별자',
	`USERNAME`	VARCHAR(45)	NOT NULL	COMMENT '유저명',
	`PASSWORD`	VARCHAR(255)	NOT NULL	COMMENT '비밀번호',
	`EMAIL`	VARCHAR(255)	NOT NULL	COMMENT '이메일',
	`ENABLED`	INT	NOT NULL	DEFAULT 1	COMMENT '사용가능 여부',
	`ROLE_TYPE`	VARCHAR(20)	NOT NULL	DEFAULT 'USER'	COMMENT '역할',
	`EMAIL_VERIFIED_YN`	INT	NOT NULL	DEFAULT 1	COMMENT '메일 인증여부',
	`PROVIDER_TYPE`	VARCHAR(20)	NOT NULL	COMMENT '소셜 제공자',
	`PROFILE_IMAGE_URL`	VARCHAR(512)	NOT NULL	COMMENT '이미지 경로',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (USERNAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_MENU(
	`MENU_CD`	VARCHAR(50)	NOT NULL	COMMENT '메뉴코드',
	`UP_MENU_CD`	VARCHAR(50)	NULL	COMMENT '상위 메뉴 코드',
	`MENU_NAME`	VARCHAR(50)	NOT NULL	COMMENT '메뉴 명',
	`URL`	VARCHAR(1000)	NULL	COMMENT 'URL',
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`USE_YN`	VARCHAR(3)	NOT NULL	DEFAULT 'Y'	COMMENT '사용가능 여부',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (MENU_CD)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_COMMON_CODE_DETAIL(
	`CODE`	VARCHAR(10)	NOT NULL	COMMENT '공통코드',
	`CODE_DETAIL_CD`	VARCHAR(10)	NOT NULL	COMMENT '상세공통코드',
	`CODE_DETAIL_NAME`	VARCHAR(20)	NOT NULL	COMMENT '상세 공통코드 명',
	`CODE_DESC`	VARCHAR(100)	NULL	COMMENT '상세 공통코드 설명',
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (CODE, CODE_DETAIL_CD)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_COMMON_CODE(
	`CODE`	VARCHAR(10)	NOT NULL	COMMENT '공통코드',
	`CODE_NAME`	VARCHAR(20)	NOT NULL	COMMENT '공통코드명',
	`CODE_DESC`	VARCHAR(100)	NULL	COMMENT '공통코드 설명',
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (CODE)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_AUTHORITIES(
	`USERNAME`	VARCHAR(45)	NOT NULL	COMMENT '유저명',
	`AUTHORITY`	VARCHAR(45)	NOT NULL	COMMENT '유저명',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (USERNAME, AUTHORITY)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_METHOD(
	`PROJECT_CODE`	VARCHAR(50)	NOT NULL	COMMENT '프로젝트 코드',
	`PACKAGE_NAME`	VARCHAR(200)	NOT NULL	COMMENT '패키지 명',
	`CLASS_NAME`	VARCHAR(50)	NOT NULL	COMMENT '클래스명',
	`METHOD`	VARCHAR(50)	NOT NULL	COMMENT '메서드명',
	`METHOD_COMMENT`	VARCHAR(200)	NULL	COMMENT '메서드 설명',
	`METHOD_ACCESS_MODIFIER`	VARCHAR(200)	NOT NULL	COMMENT '메서드 접근제한자',
	`RETURN_TYPE`	VARCHAR(200)	NOT NULL	COMMENT '리턴 타입',
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (PROJECT_CODE, PACKAGE_NAME, CLASS_NAME, METHOD)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_PACKAGE(
	`PROJECT_CODE`	VARCHAR(50)	NOT NULL	COMMENT '프로젝트 코드',
	`PACKAGE_NAME`	VARCHAR(200)	NOT NULL	COMMENT '패키지 명',
	`PACKAGE_COMMENT`	VARCHAR(200)	NULL	COMMENT '패키지 설명',
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (PROJECT_CODE, PACKAGE_NAME, PACKAGE_COMMENT)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_METHOD_VAR(
	`PROJECT_CODE`	VARCHAR(50)	NOT NULL	COMMENT '프로젝트 코드',
	`PACKAGE_NAME`	VARCHAR(200)	NOT NULL	COMMENT '패키지 명',
	`CLASS_NAME`	VARCHAR(50)	NOT NULL	COMMENT '클래스명',
	`METHOD`	VARCHAR(50)	NOT NULL	COMMENT '메서드명',
	`METHOD_VAR`	VARCHAR(200)	NOT NULL	COMMENT '메서드 변수명',
	`VAR_TYPE`	VARCHAR(200)	NOT NULL	COMMENT '변수 타입',
	`METHOD_VAR_COMMENT`	VARCHAR(200)	NULL	COMMENT '메서드 설명',
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (PROJECT_CODE, PACKAGE_NAME, CLASS_NAME, METHOD, METHOD_VAR)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_DDL(
	`PROJECT_CODE`	VARCHAR(50)	NOT NULL	COMMENT '프로젝트 코드',
	`TABLE_NAME`	VARCHAR(50)	NOT NULL	COMMENT '테이블명',
	`TABLE_COL`	VARCHAR(100)	NOT NULL	COMMENT '테이블컬럼',
	`COL_TYPE`	VARCHAR(100)	NULL	COMMENT '컬럼타입',
	`COL_TYPE_LMT`	VARCHAR(100)	NULL	COMMENT '컬럼타입제한',
	`COL_PK`	INT(100)	NULL	COMMENT 'PK',
	`NULLABLE`	INT(100)	NULL	COMMENT 'Null 여부',
	`DEFAULT_VALUE`	VARCHAR(100)	NULL	COMMENT '기본값',
	`COMMENT`	VARCHAR(100)	NULL	COMMENT '설명',
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (PROJECT_CODE, TABLE_NAME, TABLE_COL)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_CLASS_VAR(
	`PROJECT_CODE`	VARCHAR(50)	NOT NULL	COMMENT '프로젝트 코드',
	`PACKAGE_NAME`	VARCHAR(200)	NOT NULL	COMMENT '패키지 명',
	`CLASS_NAME`	VARCHAR(50)	NOT NULL	COMMENT '클래스명',
	`CLASS_VAR`	VARCHAR(50)	NOT NULL	COMMENT '클래서 변수명',
	`CLASS_VAR_COMMENT`	VARCHAR(200)	NULL	COMMENT '변수 설명',
	`CLASS_VAR_ACCESS_MODIFIER`	INT	NOT NULL	COMMENT '접근제한자',
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (PROJECT_CODE, PACKAGE_NAME, CLASS_NAME, CLASS_VAR)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_CLASS(
	`PROJECT_CODE`	VARCHAR(50)	NOT NULL	COMMENT '프로젝트 코드',
	`PACKAGE_NAME`	VARCHAR(200)	NOT NULL	COMMENT '패키지 명',
	`CLASS_NAME`	VARCHAR(50)	NOT NULL	COMMENT '클래스명',
	`CLASS_TYPE`	VARCHAR(50)	NULL	COMMENT '클래스 타입',
	`CLASS_COMMENT`	VARCHAR(200)	NULL	COMMENT '클래스 설명',
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (PROJECT_CODE, PACKAGE_NAME, CLASS_NAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_PROJECT(
	`PROJECT_CODE`	VARCHAR(50)	NOT NULL	COMMENT '프로젝트 코드',
	`PROJECT_NAME`	VARCHAR(50)	NOT NULL	COMMENT '프로젝트 명',
	`PROJECT_COMMENT`	VARCHAR(200)	NULL	COMMENT '프로젝트 설명',
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (PROJECT_CODE)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE PGI_RELATION_SHIP(
	`PROJECT_CODE`	VARCHAR(50)	NOT NULL	COMMENT '프로젝트 코드',
	`LEFT_PACKAGE`	VARCHAR(200)	NOT NULL,
	`LEFT_CLASS`	VARCHAR(50)	NOT NULL,
	`LEFT_NUMBER`	VARCHAR(50)	NOT NULL,
	`RIGHT_PACKAGE`	VARCHAR(200)	NOT NULL,
	`RIGHT_CLASS`	VARCHAR(50)	NOT NULL,
	`RIGHT_NUMBER`	VARCHAR(50)	NOT NULL,
	`RELATION`	VARCHAR(200)	NOT NULL,
	`RELATION_SHIP_COMMENT`	VARCHAR(200)	NULL,
	`SORT_SEQ`	INT	NOT NULL	COMMENT '정렬 순번',
	`INS_ID`	VARCHAR(45)	NOT NULL	COMMENT '생성 ID',
	`INS_DT`	TIMESTAMP	NOT NULL	COMMENT '생성 일시',
	`UPD_ID`	VARCHAR(45)	NOT NULL	COMMENT '수정 ID',
	`UPD_DT`	TIMESTAMP	NOT NULL	COMMENT '수정 일시',
	PRIMARY KEY (PROJECT_CODE, LEFT_PACKAGE, LEFT_CLASS, RIGHT_PACKAGE, RIGHT_CLASS, RELATION)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

