CREATE TABLE IF NOT EXISTS `USERS`(
	`USERNAME`	VARCHAR(45)		NOT NULL,
	`PASSWORD`	VARCHAR(255)	NOT NULL,
	`ENABLED`	INT 			DEFAULT 1	NOT NULL,
	PRIMARY KEY(`USERNAME`)
);

CREATE TABLE IF NOT EXISTS `AUTHORITIES`(
	`USERNAME`	VARCHAR(45)	NOT NULL,
	`AUTHORITY`	VARCHAR(45) NOT NULL,
	PRIMARY KEY(`USERNAME`)
);

CREATE TABLE IF NOT EXISTS `OTP`(
	`USERNAME`	VARCHAR(45)	NOT NULL,
	`CODE`	VARCHAR(45) NOT NULL,
	PRIMARY KEY(`USERNAME`)
);

CREATE TABLE IF NOT EXISTS `CLIENTS`(
	`CLIENTS_ID`		VARCHAR(300)	NOT NULL,
	`CLIENTS_SECRET`	VARCHAR(300)	NOT NULL,
	PRIMARY KEY(`USERNAME`)
);

CREATE TABLE IF NOT EXISTS `MENU` (
  `MENU_CD` 		VARCHAR(50) NOT NULL,
  `UP_MENU_CD` 		VARCHAR(50) NULL,
  `MENU_NAME` 		VARCHAR(50) NOT NULL,
  `URL` 			VARCHAR(100) NULL,
  `SORT_SEQ` 		INT,
  `USE_YN` 			VARCHAR(3) DEFAULT 'Y',
  `INS_ID`			VARCHAR(45)		NOT NULL,
  `INS_DT`			TIMESTAMP		NOT NULL,
  `UPD_ID`			VARCHAR(45)		NOT NULL,
  `UPD_DT`			TIMESTAMP		NOT NULL,
  PRIMARY KEY(MENU_CD)
);